services:
    # build the image and start in a bash shell
    #  To have ssh and git support, use `bin/shell`
    shell:
        build: 
          context: .
          target: dev
        command: /bin/bash # starts shell, overriding default CMD
        volumes:
            - .:/usr/local/go/src/dkman # working dir, shared with host. This *must* match WORKDIR from Dockerfile